import crypto from "crypto";

import { loadRules } from "../utils/queryRewrite.js";
import { serializeRowsToArrow } from "../utils/arrowSerializer.js";
import { validateFormat } from "../utils/formatValidator.js";
import { writeRowsAsCSV, writeTextChunk } from "../utils/csvSerializer.js";
import { buildJSONStat } from "../utils/jsonstatBuilder.js";

const { JWT_KEY } = process.env;

/**
 * Verify that SQL was generated internally by gen_sql (HMAC-signed with JWT_KEY).
 * Returns true if the signature matches, meaning the SQL came from the
 * queryRewrite-governed gen_sql pipeline and is safe to execute.
 */
function isSignedSql(sql, signature) {
  if (!signature || !JWT_KEY) return false;
  const expected = crypto
    .createHmac("sha256", JWT_KEY)
    .update(sql)
    .digest("hex");
  return crypto.timingSafeEqual(
    Buffer.from(expected, "hex"),
    Buffer.from(signature, "hex")
  );
}

const CSV_HEADERS = {
  "Content-Type": "text/csv",
  "Content-Disposition": 'attachment; filename="query-result.csv"',
};
const ARROW_HEADERS = {
  "Content-Type": "application/vnd.apache.arrow.stream",
  "Content-Disposition": 'attachment; filename="query-result.arrow"',
};
const CSV_STREAM_CHUNK_SIZE = 128 * 1024;
const CLICKHOUSE_NULL_TOKEN_RE = /(?<=,|^)\\N(?=,|\r?\n|$)/g;

/**
 * Detect whether the driver targets ClickHouse based on the datasource dbType.
 */
function isClickHouse(securityContext) {
  const dbType =
    securityContext?.userScope?.dataSource?.dbType;
  return typeof dbType === "string" && dbType.toLowerCase() === "clickhouse";
}

function normalizeClickHouseCSVLine(line) {
  const normalized = line.replace(CLICKHOUSE_NULL_TOKEN_RE, "");
  if (normalized.endsWith("\r\n")) return normalized;
  if (normalized.endsWith("\n")) return normalized.slice(0, -1) + "\r\n";
  return normalized + "\r\n";
}

function addUniqueColumns(target, names) {
  if (!Array.isArray(names)) return;
  for (let i = 0; i < names.length; i++) {
    const name = names[i];
    if (typeof name === "string" && !target.includes(name)) {
      target.push(name);
    }
  }
}

function removeTrailingSemicolon(query) {
  const trimmed = String(query ?? "").trimEnd();
  let lastNonSemiIdx = trimmed.length;
  for (let i = lastNonSemiIdx; i > 0; i--) {
    if (trimmed[i - 1] !== ";") {
      lastNonSemiIdx = i;
      break;
    }
  }
  return lastNonSemiIdx !== trimmed.length
    ? trimmed.slice(0, lastNonSemiIdx)
    : trimmed;
}

function deriveExportColumnsFromRunSql(body, rows) {
  if (rows.length > 0) {
    return Object.keys(rows[0]);
  }

  const columns = [];
  addUniqueColumns(columns, body?.columns);
  addUniqueColumns(columns, body?.dimensions);
  addUniqueColumns(columns, body?.timeDimensions);
  addUniqueColumns(columns, body?.measures);
  return columns;
}

async function writeBinaryChunk(writable, chunk, signal) {
  if (!chunk || chunk.length === 0) return;
  if (signal?.aborted) {
    throw signal.reason ?? new Error("Arrow output aborted.");
  }
  if (writable.destroyed || writable.writableEnded) {
    throw new Error("Arrow output stream is not writable.");
  }
  if (writable.write(chunk)) return;

  await new Promise((resolve, reject) => {
    const cleanup = () => {
      writable.off("drain", onDrain);
      writable.off("close", onClose);
      writable.off("error", onError);
      signal?.removeEventListener("abort", onAbort);
    };
    const onDrain = () => {
      cleanup();
      resolve();
    };
    const onClose = () => {
      cleanup();
      reject(new Error("Arrow output stream closed before it drained."));
    };
    const onError = (err) => {
      cleanup();
      reject(err);
    };
    const onAbort = () => {
      cleanup();
      reject(signal.reason ?? new Error("Arrow output aborted."));
    };

    writable.once("drain", onDrain);
    writable.once("close", onClose);
    writable.once("error", onError);
    signal?.addEventListener("abort", onAbort, { once: true });
  });
}

/**
 * Asynchronous function to run a SQL query using Cube.js.
 * Blocks access for teams with active query rewrite rules (prevents queryRewrite bypass).
 */
export default async (req, res, cubejs) => {
  const { securityContext } = req;

  if (!req.body.query) {
    res.status(400).json({
      code: "query_missing",
      message: "The query parameter is missing.",
    });

    return;
  }

  try {
    const format = validateFormat(req.body.format);
    const sql = req.body.query;

    // Block freeform SQL when access control rules are active.
    // SQL that was generated by gen_sql is HMAC-signed — if the signature
    // verifies, the SQL went through the queryRewrite-governed pipeline
    // and is safe to execute regardless of access control rules.
    if (!isSignedSql(sql, req.body.sql_signature)) {
      const rules = await loadRules();
      if (rules.length > 0) {
        res.status(403).json({
          code: "sql_api_blocked",
          message:
            "SQL API access is not available for teams with active access control rules. Use the Cube.js API instead.",
        });
        return;
      }
    }

    const driver = await cubejs.options.driverFactory({ securityContext });

    // --- JSON (default): preserve original behavior ---
    if (format === "json") {
      // Note: CUBEJS_DB_QUERY_DEFAULT_LIMIT and CUBEJS_DB_QUERY_LIMIT do NOT apply here
      // because driver.query() bypasses the Cube.js engine. The only LIMIT is whatever
      // playground_state.limit baked into the SQL by gen_sql.
      const rows = await driver.query(sql);
      const JSON_SAFETY_LIMIT = 100_000;
      if (rows.length > JSON_SAFETY_LIMIT) {
        console.warn(`JSON response truncated: ${rows.length} rows exceeded safety limit of ${JSON_SAFETY_LIMIT}`);
        rows.length = JSON_SAFETY_LIMIT;
      }
      res.json(rows);
      return;
    }

    // --- CSV / Arrow ClickHouse fast paths ---
    const abortController = new AbortController();
    let responseFinished = false;
    res.on("finish", () => {
      responseFinished = true;
    });
    res.on("close", () => {
      if (!responseFinished && !abortController.signal.aborted) {
        abortController.abort();
      }
    });

    if (format === "jsonstat") {
      const { measures, timeDimensions } = req.body;
      const rows = await driver.query(sql);
      const columns = deriveExportColumnsFromRunSql(req.body, rows);
      const dataset = buildJSONStat(rows, columns, { measures, timeDimensions });

      if (dataset.error) {
        res.status(dataset.status || 400).json({ error: dataset.error });
        return;
      }

      res.set("Content-Type", "application/json");
      res.set("Content-Disposition", 'attachment; filename="query-result.json"');
      res.json(dataset);
      return;
    }

    if (format === "arrow" && isClickHouse(securityContext)) {
      const clickhouseQuery = `${removeTrailingSemicolon(sql)}\nFORMAT ArrowStream`;
      const result = await driver.client.exec({
        query: clickhouseQuery,
        clickhouse_settings: {
          ...driver.config?.clickhouseSettings,
          output_format_arrow_compression_method: "none",
        },
        abort_signal: abortController.signal,
      });

      res.set(ARROW_HEADERS);

      try {
        for await (const chunk of result.stream) {
          await writeBinaryChunk(res, chunk, abortController.signal);
        }
      } catch (streamErr) {
        if (abortController.signal.aborted) return;
        throw streamErr;
      }

      res.end();
      return;
    }

    if (format === "csv" && isClickHouse(securityContext)) {
      // ClickHouse fast path: stream CSV directly from the server (constant memory)

      const resultSet = await driver.client.query({
        query: sql,
        format: "CSVWithNames",
        clickhouse_settings: driver.config?.clickhouseSettings,
        abort_signal: abortController.signal,
      });

      res.set(CSV_HEADERS);

      try {
        // Stream CSV rows directly from ClickHouse to the response
        let chunk = "";
        for await (const rows of resultSet.stream()) {
          for (const row of rows) {
            // row.text contains one CSV line; normalize ClickHouse nulls and
            // line endings so the generic and ClickHouse paths match.
            chunk += normalizeClickHouseCSVLine(row.text);
            if (chunk.length >= CSV_STREAM_CHUNK_SIZE) {
              await writeTextChunk(res, chunk, abortController.signal);
              chunk = "";
            }
          }
        }
        if (chunk.length > 0) {
          await writeTextChunk(res, chunk, abortController.signal);
        }
      } catch (streamErr) {
        // Client disconnect triggers abort — not a real error
        if (abortController.signal.aborted) return;
        throw streamErr;
      }

      res.end();
      return;
    }

    const rows = await driver.query(sql);

    if (format === "arrow") {
      // Generic (non-ClickHouse) Arrow path buffers all rows + 4x memory
      // amplification in serializeRowsToArrow.  Apply the same safety limit
      // as JSON to prevent OOM / V8 string-size crashes.
      const ARROW_SAFETY_LIMIT = 100_000;
      if (rows.length > ARROW_SAFETY_LIMIT) {
        console.warn(`Arrow response truncated: ${rows.length} rows exceeded safety limit of ${ARROW_SAFETY_LIMIT}`);
        rows.length = ARROW_SAFETY_LIMIT;
      }
      const columns = deriveExportColumnsFromRunSql(req.body, rows);
      res.set(ARROW_HEADERS);
      res.send(serializeRowsToArrow(rows, { columns }));
      return;
    }

    if (!rows || rows.length === 0) {
      res.set(CSV_HEADERS);
      res.set("Content-Length", "0");
      res.send("");
      return;
    }

    res.set(CSV_HEADERS);
    await writeRowsAsCSV(res, rows, { signal: abortController.signal });
    res.end();
  } catch (err) {
    console.error(err);

    if (res.headersSent) {
      if (!res.writableEnded) res.end();
      return;
    }

    res.status(err.status || 500).json({
      code: "run_sql_failed",
      message: err.message || err,
    });
  }
};
