name: Build and push stack (DEPRECATED - replaced by build-containers.yml)

on:
  # Disabled - replaced by selective build workflow
  # push:
  #   branches:
  #     - master
  #     - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push stack image
        run: |
          docker compose -f docker-compose.stack.yml build && \
          docker compose -f docker-compose.stack.yml push

      - name: Build and push services images
        run: |
          export REGISTRY_HOST=index.docker.io && \
          export DOMAIN=synmetrix.org && \
          docker compose -f docker-compose.stage.yml build && \
          docker compose -f docker-compose.stage.yml push
